

export enum textTypes {
  TITLE_BOLD = 'TITLE', //24px
  TITLE_SEMI_BOLD = 'TITLE',
  TITLE_REGULAR = 'TITLE_REGULAR',
  TITLE_LIGHT = 'TITLE_LIGHT',
  SUBTITLE_BOLD = 'SUBTITLE', //20px
  SUBTITLE_SEMI_BOLD = 'SUBTITLE', //20px
  SUBTITLE_REGULAR = 'SUBTITLE_REGULAR',
  SUBTITLE_LIGHT = 'SUBTITLE_LIGHT',
  BUTTON_BOLD = 'BUTTON', //18px
  BUTTON_SEMI_BOLD = 'BUTTON', //18px
  BUTTON_REGULAR = 'BUTTON_REGULAR',
  BUTTON_LIGHT = 'BUTTON_LIGHT',
  PARAGRAPH_BOLD = 'PARAGRAPH', //14px
  PARAGRAPH_SEMI_BOLD = 'PARAGRAPH', //14px
  PARAGRAPH_REGULAR = 'PARAGRAPH_REGULAR',
  PARAGRAPH_LIGHT = 'PARAGRAPH_LIGHT',
  PARAGRAPH_SMALL_BOLD = 'PARAGRAPH_SMALL', //10px
  PARAGRAPH_SMALL_SEMI_BOLD = 'PARAGRAPH_SMALL', //10px
  PARAGRAPH_SMALL_REGULAR = 'PARAGRAPH_SMALL_REGULAR',
  PARAGRAPH_SMALL_LIGHT = 'PARAGRAPH_SMALL_LIGHT',
  
}